site_name = "Fully Vegan Recipes"
author_name = "Fully Vegan Recipes"
about = """
<p><a href="/posts/1">Baguette</a> <br />\r
<a href="/posts/3">Burger Buns</a> <br />\r
<a href="/posts/4">Chickpeas Salad</a> <br />\r
<a href="/posts/5">Cinnamon Rolls</a> <br />\r
<a href="/posts/19">Cookies</a> <br />\r
<a href="/posts/6">Enchiladas (Burritos)</a> <br />\r
<a href="/posts/7">Falafel</a> <br />\r
<a href="/posts/8">Gingerbread Cookies</a> <br />\r
<a href="/posts/9">Hummus</a> <br />\r
<a href="/posts/10">Kartoffelsalat</a> <br />\r
<a href="/posts/11">Lasagna</a> <br />\r
<a href="/posts/12">Mushroom Spaghetti</a> <br />\r
<a href="/posts/13">Pancakes</a> <br />\r
<a href="/posts/14">Pasta Salad</a> <br />\r
<a href="/posts/15">Potato Savoy Cabbage</a> <br />\r
<a href="/posts/16">Pumpkin Cake</a> <br />\r
<a href="/posts/17">Pumpkin Soup</a> <br />\r
<a href="/posts/2">Spaghetti with Beetroot Sauce</a> <br />\r
<a href="/posts/18">Tikka Masala</a></p>"""
