site_name = "Fully Vegan Recipes"
author_name = "Fully Vegan Recipes"
about = """
<div style='text-align: center; font-size: 1.1rem;'>
<div style='display: inline-block;'>
  <a href='/posts/1'>Baguette</a><br>
  <a href='/posts/3'>Burger Buns</a><br>
  <a href='/posts/4'>Chickpeas Salad</a><br>
  <a href='/posts/5'>Cinnamon Rolls</a><br>
  <a href='/posts/19'>Cookies</a><br>
  <a href='/posts/6'>Enchiladas (Burritos)</a><br>
  <a href='/posts/7'>Falafel</a><br>
  <a href='/posts/8'>Gingerbread Cookies</a><br>
  <a href='/posts/9'>Hummus</a><br>
  <a href='/posts/10'>Kartoffelsalat</a><br>
  <a href='/posts/24'>Kichererbsen Rührei</a><br>
</div>
<div style='display: inline-block; vertical-align: top;'>
  <a href='/posts/11'>Lasagna</a><br>
  <a href='/posts/12'>Mushroom Spaghetti</a><br>
  <a href='/posts/13'>Pancakes</a><br>
  <a href='/posts/14'>Pasta Salad</a><br>
  <a href='/posts/15'>Potato Savoy Cabbage</a><br>
  <a href='/posts/16'>Pumpkin Cake</a><br>
  <a href='/posts/17'>Pumpkin Soup</a><br>
  <a href='/posts/20'>Sauerteig Discard Cracker</a><br>
  <a href='/posts/2'>Spaghetti with Beetroot Sauce</a><br>
  <a href='/posts/18'>Tikka Masala</a><br>
  <a href='/posts/23'>Vollkorn Sauerteigbrot</a><br>
</div>
</div>"""
